version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/node:lts
    environment:
      TZ: 'Asia/Tokyo'
  rails:
    docker:
      - image: cimg/ruby:2.7.1-node
    environment:
      BUNDLE_PATH: vendor/bundle

commands:
  sayhello:
    description: "Say Hello"
    parameters:
      to:
        type: string
        default: "World"
    steps:
      - run: echo Hello << parameters.to >>

jobs:
  install:
    executor:
      name: my-executor
    steps:
      - checkout
      - run: yarn install
      - persist_to_workspace:
          root: /home/circleci/projects/
          paths:
            - node_modules
  test:
    executor:
      name: my-executor
    steps:
      - attach_workspace:
          at: /home/circleci/projects/node_modules
      - checkout
      - run: yarn test
      - sayhello:
          to: JavaScript
  railsapp:
    executor:
      name: rails
    docker: # overwride executor definitions
      - image: cimg/ruby:2.7.1
    environment:
      RAILS_ENV: production
    steps:
      - run: echo Hello World
      - sayhello:
          to: Everyone

workflows:
  version: 2
  workflow:
    jobs:
      - install
      - test:
          requires:
            - install
      - railsapp:
          requires:
            - test
