version: 2.1
executors:
  default: # executorに予約名等はなく、人が判断するためだけのもの
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo # デフォルト値は ~/project

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Nodeモジュールのインストール
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  test_jest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Jestを実行
          command: npx jest --ci --maxWorkers=2

workflows:
  version: 2
  build_test:
    jobs: # 各jobを並列実行
      - setup
      - test_jest:
          requires: # jobの実行順序を制御し setup のあとに実行
            - setup
