version: 2.1
executors:
  default: # executorに予約名等はなく、人が判断するためだけのもの
    docker:
      - image: cimg/node:lts
    environment:
      TZ: 'Asia/Tokyo'
    working_directory: ~/repo # デフォルト値は ~/project
  with_db:
    docker:
      - image: cimg/ruby:2.7.1-node
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/mysql:8.0.18-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: sample-circleci_test
        command: mysqld --default-authentication-plugin=mysql_native_password
    working_directory: ~/repo

jobs:
  setup_node:
    executor: default
    steps:
      - checkout
      - run:
          name: Nodeモジュールのインストール
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          paths:
            - node_modules
  test_jest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Jestを実行
          command: npx jest --ci --maxWorkers=2
  test_rspec:
    executor: with_db
    steps:
      - checkout
      - run:
          name: install gems
          command: bundle install
      - run:
          name: wait for DB up
          command: |
            dockerize -wait tcp://${DB_HOST}:3306 -timeout 120s
      - run:
          name: setup DB
          command: bundle exec rake db:schema:load --trace
      - run:
          name: run rspec
          command: bundle exec rspec

workflows:
  version: 2
  build_test:
    jobs: # 各jobを並列実行
      - setup_node
      - test_jest:
          requires: # jobの実行順序を制御し setup のあとに実行
            - setup_node
      - test_rspec
